### ISSUE TITLE
Go code storing Go pointers in C memory

### ISSUE THREAD

**Issue by zagrodzki** [google/gousb#10]
libusb.alloc() stores a Go pointer (&buf[0]) in C memory (xfer struct allocated by C.libusb_alloc_transfer).
The buffer should be owned by C code.
Thanks to @codido for the report.

**Comment by zagrodzki** [comment]
and here's a clear example with GODEBUG=cgocheck=2:

```
2017/08/29 00:49:59 Found endpoint: ep #1 IN (address 0x81) isochronous - asynchronous data [3072 bytes]
2017/08/29 00:49:59 Reading...
write of Go pointer 0xc4200aa000 to non-Go memory 0x9d54a0
fatal error: Go pointer stored into non-Go memory

runtime stack:
runtime.throw(0x4f097a, 0x24)
	/home/sebek/go/src/runtime/panic.go:596 +0x95
runtime.cgoCheckWriteBarrier.func1()
	/home/sebek/go/src/runtime/cgocheck.go:44 +0xb8
runtime.systemstack(0x768900)
	/home/sebek/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/home/sebek/go/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/sebek/go/src/runtime/asm_amd64.s:281 fp=0xc42004d928 sp=0xc42004d920
runtime.cgoCheckWriteBarrier(0x9d54a0, 0xc4200aa000)
	/home/sebek/go/src/runtime/cgocheck.go:45 +0xb6 fp=0xc42004d960 sp=0xc42004d928
runtime.writebarrierptr(0x9d54a0, 0xc4200aa000)
	/home/sebek/go/src/runtime/mbarrier.go:199 +0xcc fp=0xc42004d998 sp=0xc42004d960
github.com/google/gousb.libusbImpl.alloc(0x9d5350, 0xc42009e028, 0x0, 0x1, 0xc4200aa000, 0x400, 0x400, 0xc420098180, 0xc420098180, 0x0, ...)
	/home/sebek/golang/src/github.com/google/gousb/libusb.go:424 +0x19b fp=0xc42004da08 sp=0xc42004d998
github.com/google/gousb.(*libusbImpl).alloc(0x782a60, 0x9d5350, 0xc42009e028, 0x0, 0x1, 0xc4200aa000, 0x400, 0x400, 0xc420098180, 0x0, ...)
	<autogenerated>:98 +0xab fp=0xc42004da70 sp=0xc42004da08
github.com/google/gousb.newUSBTransfer(0x9d5350, 0xc42009e028, 0xc4200aa000, 0x400, 0x400, 0x0, 0x80, 0x7685e0, 0xa)
	/home/sebek/golang/src/github.com/google/gousb/transfer.go:126 +0x24d fp=0xc42004db50 sp=0xc42004da70
github.com/google/gousb.(*endpoint).transfer(0xc42009e000, 0xc4200aa000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/sebek/golang/src/github.com/google/gousb/endpoint.go:92 +0x8f fp=0xc42004dbb0 sp=0xc42004db50
github.com/google/gousb.(*InEndpoint).Read(0xc4200a0000, 0xc4200aa000, 0x400, 0x400, 0x400, 0x400, 0x0)
	/home/sebek/golang/src/github.com/google/gousb/endpoint.go:119 +0x4c fp=0xc42004dbf8 sp=0xc42004dbb0
main.main()
	/home/sebek/golang/src/github.com/google/gousb/rawread/main.go:174 +0xdab fp=0xc42004df88 sp=0xc42004dbf8
```

**Comment by zagrodzki** [comment]
Tested with GODEBUG=cgocheck=2, looks good.
